---
- name: Criação e registro de pares de chave
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars_files:
    - vars/global.yml

  environment:
    AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
    AWS_SESSION_TOKEN: "{{ lookup('env', 'AWS_SESSION_TOKEN') }}"

  tasks:

    - name: Criação de pares de chave
      community.crypto.openssh_keypair:
        path: "{{ playbook_dir }}/{{ access_key }}"
        size: 4096
        type: rsa
        force: true
        mode: 0600
        register: keypair_result

    - name: Registro de par de chaves no EC2
      amazon.aws.ec2_key:
        name: "{{ access_key }}"
        region: "{{ aws_region }}"
        key_material: "{{ keypair_result.public_key }}"
        force: true
     
