---
- name: Criação de Instância
  hosts: localhost
  connection: local
  gather_facts: false
  become: true
  vars_files:
    - vars/global.yml
    - vars/vpc.yml
    - vars/instance.yml

  environment:
    AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
    AWS_SESSION_TOKEN: "{{ lookup('env', 'AWS_SESSION_TOKEN') }}"

  vars:
    subnet_id: "{{ hostvars['virtual_host']['subnet_id'] }}"
  
  tasks:
    - name: configura bibliotecas Python
      import_tasks: setup-python.yml   

    - name: Provisionamento de instância
      ec2:
         key_name: "{{ access_key }}"
         groups: "{{ security_group_name }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image_id }}"
         wait: true
         region: "{{ aws_region }}"
         assign_public_ip: yes
         vpc_subnet_id: "{{ subnet_id }}"
         AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
         AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
         AWS_SESSION_TOKEN: "{{ lookup('env', 'AWS_SESSION_TOKEN') }}"

         user_data: |
            #!/bin/bash -xe
            /bin/sed -ri '/Defaults[ ]{1,}requiretty/d' -i /etc/sudoers
         termination_protection: yes

         instance_tags:
             Name: "new-server-name"

         volumes:
           - device_name: /dev/sda1
             volume_type: gp2
             volume_size: 8
             
      register: ec2      
      
        deployable: true
        wait: yes
        state: running
      register: ec2_result
